# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b79a0f9ed19ba6a44f287c4d5b587f0f64ec40e18f9cdcba3f0055a2a4285297a34fcb3f0aef65b15d34981ae5b0d6023f83e865a2455b7e7b8e1a0d8fce0ff1

test:
  secret_key_base: 65ecd15716202db7df9c3713aac74cc50e73ffc08cdfae14c3ff7b0ead53ef01119f5532c7a1876f15fb3fa1809f5372400b8bd4667ff4a150d9a451467f1376

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
